# Generated by Django 4.1.7 on 2023-07-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=40, verbose_name='ФИО')),
                ('job_title', models.CharField(max_length=75, verbose_name='Работа')),
                ('summ', models.CharField(max_length=7, verbose_name='Деньги')),
                ('url_progect', models.CharField(max_length=250, verbose_name='Сылка на проект')),
            ],
        ),
    ]
